spring:
  application:
    name: leave-service
  config:
    import: optional:configserver:http://localhost:8888

# Server Configuration
server:
  port: 8087

# Logging Configuration
logging:
  level:
    com.hermes.leaveservice: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.cloud.config: DEBUG
    org.springframework.boot.autoconfigure: DEBUG

# Leave Service Configuration
leave:
  max-annual-leave: 15
  max-sick-leave: 10

# Eureka Client Configuration
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
