spring:
  application:
    name: communication-service
  config:
    import: optional:configserver:http://localhost:8888

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8086
  servlet:
    context-path: /communication-api

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true